config/routes.rb
Sandbox::Application.routes.draw do
  get "auth/facebook"

  root :to => 'Users#root'
  
  resources :users
  
  resource :session, :only => [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :facebook_access_token, :facebook_id, :location, :name, :password, :password_confirmation
  
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :logged_in?, :current_user
  
  def logged_in?
    session[:user_id].present? && current_user.present?
  end
  
  def current_user
    User.find_by_id(session[:user_id])
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def facebook
  @state = params["state"]
  @code = params["code"]

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if (user = User.find_by_email(params[:email])) && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user, :notice => "Sign-in successful."
    else
      redirect_to root_url, :notice => "Sign-in unsuccessful."
    end
  end
  
  def destroy
    reset_session
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:show, :edit, :update, :delete]
  
  def require_login
    if session[:user_id] && session[:user_id] == params[:id].to_i
      @user = current_user   
    else
      redirect_to root_url, :notice => "Not authorized for that."
    end
  end
  
  def root
    if logged_in?
      @user = current_user
      render 'show'
    else
      @users = User.all
      render 'index'
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Sign-up successful.'
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Update successful.'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy

    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sandbox" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    <link href='http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica:400,400italic' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        <h1><%= link_to "Sandbox", root_url %></h1>
      </div><!--/row-->
      <div class="row-fluid">
        <% if logged_in? %>
          <%= link_to "Sign Out", session_url, :method => 'delete' %>
        <% else %>
          <%= link_to "Sign Up", new_user_url %> or Sign In:
          <%= form_tag session_url do %>
            <%= text_field_tag :email %>
            <%= password_field_tag :password %>
            <%= submit_tag "Sign In" %>
          <% end %>
        <% end %>
      </div><!--/row-->
      <div class="row-fluid">
        <div class="span9">
          <p><%= notice %></p>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:facebook_id) %></th>
      <th><%= model_class.human_attribute_name(:facebook_access_token) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user %></td>
        <td><%= user.facebook_id %></td>
        <td><%= user.facebook_access_token %></td>
        <td><%= user.name %></td>
        <td><%= user.location %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User</h1>
</div>

<dl class="dl-horizontal">
<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Facebook:</strong> <%= @user.facebook_id %></p>
<p><strong>Facebook Access Token:</strong> <%= @user.facebook_access_token %></p>
<p><strong>Name:</strong> <%= @user.name %></p>
<p><strong>Location:</strong> <%= @user.location %></p>

<%= link_to "Login with Facebook", 'https://www.facebook.com/dialog/oauth?
    client_id=140451889436567
   &redirect_uri=http://localhost:3000/auth/facebook
   &state=SOME_ARBITRARY_BUT_UNIQUE_STRING' %>